before_script:
  - export PATH=$PATH:/usr/local/bin

stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project GeoJsonUtilsApp/GeoJsonUtilsApp.xcodeproj -scheme GeoJsonUtilsApp | xcpretty
    - xcodebuild test -project GeoJsonUtilsApp/GeoJsonUtilsApp.xcodeproj -scheme GeoJsonUtilsApp -destination 'platform=iOS Simulator,name=iPhone Xs,OS=latest' | xcpretty -s


