name: iOS-CI

on:
  push:
    branches:
      - development
      - master
      - release/*
      - hotfix/*


jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Cache Project
      id: cache-project
      uses: actions/cache@v1
      with:
        path: .
        key: ${{ runner.os }}-geojsonutils-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-geojsonutils-${{ github.sha }}
      
    - name: Lint
      run: swiftlint

    - name: Build for macOS
      run: swift build -v

    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme geojsonutils -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" -quiet

  test:
    needs: build

    runs-on: macos-latest

    steps:
    - name: Cache Project
      id: cache-project
      uses: actions/cache@v1
      with:
        path: .
        key: ${{ runner.os }}-geojsonutils-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-geojsonutils-${{ github.sha }}

    - name: Run macOS tests
      run: swift test -v

    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme geojsonutils -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" -quiet