name: CI

on: [push, pull_request]
  branches:
    - master
    - develop
    - 'release/*'
    - 'hotfix/*'


jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Building the project.
      run:
        xcodebuild clean -project GeoJsonUtilsApp/GeoJsonUtilsApp.xcodeproj -scheme GeoJsonUtilsApp | xcpretty
        
  test:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Running the project's tests.
      run:
        xcodebuild test -project GeoJsonUtilsApp/GeoJsonUtilsApp.xcodeproj -scheme GeoJsonUtilsApp -destination 'platform=iOS Simulator,name=iPhone Xs,OS=latest' | xcpretty -s
