name: iOS-CI

on:
  push:
    branches:
      - development
      - master
      - release/*
      - hotfix/*


jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Cache Project
      id: cache-project
      uses: actions/cache@v1
      with:
        path: .
        key: ${{ runner.os }}-geojsonutils-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-geojsonutils-${{ github.sha }}

    - name: Install xcpretty
      run: gem install xcpretty
    
    - name: Cleaning the project...
      run:
       xcodebuild \
       -project GeoJsonUtilsApp/GeoJsonUtilsApp.xcodeproj \
       -scheme GeoJsonUtilsApp \
       clean | xcpretty

    - name: Build app
      run: |
        xcodebuild  \
          -project GeoJsonUtilsApp/GeoJsonUtilsApp.xcodeproj \
          -scheme GeoJsonUtilsApp \
          -derivedDataPath ./derivedData \
          -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' \
          build-for-testing | xcpretty && exit ${PIPESTATUS[0]}

  test:
    needs: build

    runs-on: macos-latest
    
    steps:

    - name: Cache Project
      id: cache-project
      uses: actions/cache@v1
      with:
        path: .
        key: ${{ runner.os }}-geojsonutils-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-geojsonutils-${{ github.sha }}

    - name: Run Unit Tests
      run: |
        xcodebuild  \
          -project GeoJsonUtilsApp/GeoJsonUtilsApp.xcodeproj \
          -scheme GeoJsonUtilsApp \
          -derivedDataPath ./derivedData \
          -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' \
          test-without-building | xcpretty && exit ${PIPESTATUS[0]}